# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [1]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [3]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [4]:
#calculo de la norma del producto A
norm_A = np.linalg.norm(producto_A)
print(f'La norma del propducto A es: {norm_A}')

#calculo de la norma del producto B
norm_B = np.linalg.norm(producto_B)
print(f'La norma del producto B es: {norm_B}')

#calculo de la norma del producto C
norm_C = np.linalg.norm(producto_C)
print(f'La norma del producto C es> {norm_C}')


La norma del propducto A es: 7.449161026585477
La norma del producto B es: 6.777167549942971
La norma del producto C es> 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [5]:
#calculo del producto punto entre producto A y B
pp_AB = np.dot(producto_A, producto_B)

#calculo del producto punto entre producto A y C
pp_AC = np.dot(producto_A, producto_C)

#calculo del angulo entre producto A y B
cos_theta_AB = pp_AB / (norm_A * norm_B)
theta_rad_AB = np.arccos(cos_theta_AB)
theta_deg_AB = round(np.degrees(theta_rad_AB),2)
print(f'El angulo entre productos A y B es: {theta_deg_AB} grados.')

#calculo del angulo entre producto A y C
cos_theta_AC = pp_AC / (norm_A * norm_C)
theta_rad_AC = np.arccos(cos_theta_AC)
theta_deg_AC = round(np.degrees(theta_rad_AC),2)
print(f'El angulo entre los productos A y C es: {theta_deg_AC} grados.')


El angulo entre productos A y B es: 1.77 grados.
El angulo entre los productos A y C es: 47.23 grados.


En base a los calculos, el producto B es mas similar al producto A porque tiene un angulo mas cerrado
La similitud del coseno es util ya que mide la direccion de los vectores, no el tamano, el angulo detecta un perfil o comportamiento similar entre ambos productos


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [8]:
#obtencion del vector unitario del producto A
unitario_A = producto_A / norm_A
print(f'La norma del vector del producto A es {np.linalg.norm(unitario_A)}')

#obtencion del vector unitario del producto B
unitario_B = producto_B / norm_B
print(f'La norma del vector unitario del producto B es {np.linalg.norm(unitario_B)}')

#obtencion del vector unitario del producto C
unitario_C = producto_C / norm_C
print(f'La norma del vector unitario del producto C es {np.linalg.norm(unitario_C)}')




La norma del vector del producto A es 1.0
La norma del vector unitario del producto B es 1.0
La norma del vector unitario del producto C es 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [9]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [10]:
#multiplicacion de los valores de ambos arreglos
#se multiplica cada elemento de la misma fila y columna por el otro elemento de la otra matriz
#este proceso No sigue la regla de multiplicacion matricial
mul = M * P
print(mul, '\n')

#multiplicacion matricial, se respetan las reglas de calculo para cada elemento
#de cada matriz, hay un orden establecido
mul_mat = M @ P
print(mul_mat, '\n')

#se invierten los factores, en el caso de multiplocacion matricial, si se altera el producto
#ya que la propiedad conmutativa no aplica para multiplicacioens entre matrices
mul_mat_2 = P @ M
print(mul_mat_2)


[[3. 0.]
 [0. 6.]] 

[[3.  2. ]
 [1.5 6. ]] 

[[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [11]:
#calculo del determinante de M
det_M = np.linalg.det(M)
#se puede comprobar que la matriz tiene una determinante distinto de cero, pro lo que si tiene inversa
print(f'El determinante de la matriz M es: {det_M} \n')

#calculo del a inversa de la matriz
inv_M = np.linalg.inv(M)
print(f'La inversa de la matriz M es: \n{inv_M} \n')

#se comprueba que la multiplicacion de la matriz con su inversa,
#dan la matriz identidad
ident_M = M @ inv_M
print(f'La matriz identidad es: \n{np.round(ident_M)}')


El determinante de la matriz M es: 5.000000000000001 

La inversa de la matriz M es: 
[[ 0.6 -0.2]
 [-0.2  0.4]] 

La matriz identidad es: 
[[ 1.  0.]
 [-0.  1.]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [12]:
b = np.array([180, 300])
#se realiza la solucion del sistema de ecuaciones
x = np.linalg.solve(M, b)
print(f'Se necesita {x[0]} de insumo X, y de insumo Y {x[1]}\n')

#se procede con la verificacion de la solucion
verificacion = M @ x
print(verificacion)


Se necesita 48.0 de insumo X, y de insumo Y 84.0

[180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [13]:
#calculo de la distancia euclidiana entre producto A y B
dist_AB = np.linalg.norm(producto_B - producto_A)
print(dist_AB, '\n')
#calculo de la distancia euclidiana entre producto A y C
dist_AC = np.linalg.norm(producto_C - producto_A)
print(dist_AC, '\n')
#calculo de la similitud coseno entre productos A y B
sim_cos_AB = np.dot(producto_A, producto_B) / (norm_A * norm_B)
print(sim_cos_AB, '\n')
#calculo de la similitud coseno entre productos A y C
sim_cos_AC = np.dot(producto_A, producto_C) / (norm_A * norm_C)
print(sim_cos_AC, '\n')

#en distancia euclidiana, un valor menor indica mayor parecido en productos
prod_dist = 'B' if dist_AB < dist_AC else 'C'

#en similitud conseno, un valor mayor indica mayor parecido
prod_cos = 'B' if sim_cos_AB > sim_cos_AC else 'C'

#se evaluan ambas condiciones para ver si hay coincidncia
if prod_dist == prod_cos:
    mensaje = f'El producto mas parecido al producto A es el {prod_dist} ya que ambas metricas coinciden con el criterio'
else:
    mensaje = 'las metricas de la distancia euclidiana y similitud coseno no coinciden con el criterio'

print(mensaje)


0.7071067811865476 

5.470831746635972 

0.9995203969214979 

0.6791199021706347 

El producto mas parecido al producto A es el B ya que ambas metricas coinciden con el criterio


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.